# Generated by Django 4.0.8 on 2023-06-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_studentclass_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='sections',
            field=models.ManyToManyField(help_text='Select None if class ha no sections', to='academics.classsection'),
        ),
    ]
