# Generated by Django 4.0.8 on 2023-06-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_studentclass_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='name',
            field=models.CharField(choices=[('Term I', 'Form I'), ('Term II', 'Form II'), ('Term III', 'Form III')], max_length=20, unique=True),
        ),
    ]
