# Generated by Django 4.0.8 on 2023-06-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_academicterm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='name',
            field=models.CharField(choices=[('Term I', 'Term I'), ('Term II', 'Term II'), ('Term III', 'Term III')], max_length=20, unique=True),
        ),
    ]
