# Generated by Django 4.0.8 on 2023-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_academicterm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='name',
            field=models.CharField(choices=[('Form I', 'Form I'), ('Form II', 'Form II'), ('Form III', 'Form III'), ('Form IV', 'Form IV')], max_length=200, unique=True),
        ),
    ]
